export const BAKERY_REVIEWS = [
  {
    id: 1,
    bakeryId: 1,
    author: '소금빵마스터',
    avatarEmoji: '🧂',
    rating: 5,
    content: '겉바속촉이라는 말이 여기서 나온 듯. 평일 오전 8시 전에 가면 웨이팅 없이 살 수 있어요.',
    createdAt: '2026-07-10',
    heartCount: 52,
  },
  {
    id: 2,
    bakeryId: 1,
    author: '빵지순례자',
    avatarEmoji: '🥾',
    rating: 4.5,
    content: '버터향이 진하고 짠맛 밸런스가 좋아요. 다만 오후엔 품절이 많아서 오전 방문 추천.',
    createdAt: '2026-07-05',
    heartCount: 28,
  },
  {
    id: 3,
    bakeryId: 2,
    author: '뷰맛집헌터',
    avatarEmoji: '📷',
    rating: 4,
    content: '바다 보면서 먹는 크림치즈 바게트 조합 최고. 주말엔 자리 잡기 어려워요.',
    createdAt: '2026-07-02',
    heartCount: 19,
  },
  {
    id: 4,
    bakeryId: 3,
    author: '딸기덕후',
    avatarEmoji: '🍓',
    rating: 4,
    content: '크로플이 생각보다 두꺼워서 젤라또랑 같이 먹으면 든든해요.',
    createdAt: '2026-06-28',
    heartCount: 15,
  },
  {
    id: 5,
    bakeryId: 4,
    author: '단팥소보로',
    avatarEmoji: '🍥',
    rating: 5,
    content: '오픈 30분 만에 크루아상 다 팔릴 뻔... 겨우 득템했습니다. 겹겹이 살아있고 버터향이 진해요.',
    createdAt: '2026-07-14',
    heartCount: 34,
  },
  {
    id: 6,
    bakeryId: 4,
    author: '새벽러너',
    avatarEmoji: '🌅',
    rating: 4.5,
    content: '오픈런 필수인 집. 그래도 그만한 가치가 있어요.',
    createdAt: '2026-07-08',
    heartCount: 22,
  },
  {
    id: 7,
    bakeryId: 5,
    author: '식빵요정',
    avatarEmoji: '🍞',
    rating: 4,
    content: '단팥크림빵이 옛날 감성 그대로예요. 크림이 과하지 않아서 좋았어요.',
    createdAt: '2026-06-30',
    heartCount: 12,
  },
  {
    id: 8,
    bakeryId: 6,
    author: '치즈러버',
    avatarEmoji: '🧀',
    rating: 4.5,
    content: '치즈가 실처럼 늘어나요. 소금빵 위에 치즈 토핑 신메뉴 강추합니다.',
    createdAt: '2026-07-13',
    heartCount: 45,
  },
  {
    id: 9,
    bakeryId: 7,
    author: '식빵요정',
    avatarEmoji: '🍞',
    rating: 4.5,
    content: '줄 서서 산 우유식빵, 집 가는 길에 다 먹을 뻔했어요. 완전 폭신폭신.',
    createdAt: '2026-07-14',
    heartCount: 21,
  },
  {
    id: 10,
    bakeryId: 7,
    author: '빵지순례자',
    avatarEmoji: '🥾',
    rating: 4,
    content: '50년 전통이라는 게 느껴지는 담백한 식빵이에요.',
    createdAt: '2026-06-20',
    heartCount: 9,
  },
  {
    id: 11,
    bakeryId: 8,
    author: '새벽러너',
    avatarEmoji: '🌅',
    rating: 4,
    content: '찹쌀도넛을 즉석에서 튀겨줘서 겉은 바삭 속은 쫀득해요.',
    createdAt: '2026-06-25',
    heartCount: 14,
  },
  {
    id: 12,
    bakeryId: 9,
    author: '딸기덕후',
    avatarEmoji: '🍓',
    rating: 5,
    content: '이번엔 딸기라떼 크림까지 추가됐다는 소식! 당장 달려갑니다.',
    createdAt: '2026-07-12',
    heartCount: 58,
  },
  {
    id: 13,
    bakeryId: 9,
    author: '단팥소보로',
    avatarEmoji: '🍥',
    rating: 4.5,
    content: '딸기 시즌 한정이라 더 특별한 케이크. 당도 조절이 잘 되어있어요.',
    createdAt: '2026-07-01',
    heartCount: 31,
  },
  {
    id: 14,
    bakeryId: 10,
    author: '뷰맛집헌터',
    avatarEmoji: '📷',
    rating: 4.5,
    content: '광안대교 배경으로 피낭시에 찍으니 인생샷 나왔습니다.',
    createdAt: '2026-07-08',
    heartCount: 73,
  },
  {
    id: 15,
    bakeryId: 11,
    author: '새벽러너',
    avatarEmoji: '🌅',
    rating: 5,
    content: '새벽 5시 50분에 도착해서 1등으로 모닝빵 세트 득템했습니다 ㅎㅎ',
    createdAt: '2026-07-11',
    heartCount: 67,
  },
  {
    id: 16,
    bakeryId: 12,
    author: '한옥러버',
    avatarEmoji: '⛩️',
    rating: 5,
    content: '한옥 마당에서 흑임자 앙버터빵과 함께 찍은 사진 공유해요. 맛도 분위기도 만점.',
    createdAt: '2026-07-07',
    heartCount: 41,
  },
  {
    id: 17,
    bakeryId: 12,
    author: '빵지순례자',
    avatarEmoji: '🥾',
    rating: 4.5,
    content: '흑임자 앙버터가 고소하고 달지 않아서 계속 손이 가요.',
    createdAt: '2026-06-18',
    heartCount: 20,
  },
  {
    id: 18,
    bakeryId: 13,
    author: '한옥러버',
    avatarEmoji: '⛩️',
    rating: 4,
    content: '동래온천 나들이 후 들르기 좋은 조용한 크림빵집이에요.',
    createdAt: '2026-06-15',
    heartCount: 11,
  },
]
