export const BAKERIES = [
  {
    id: 1,
    name: '해운대 소금빵공방',
    districtId: 'haeundae',
    address: '부산 해운대구 구남로 12',
    signatureMenu: '솔티드버터롤',
    rating: 4.5,
    heartCount: 212,
    tags: ['소금빵', '오픈런'],
    emoji: '🥐',
    description: '겉바속촉 소금빵으로 매일 아침 줄서는 집.',
  },
  {
    id: 2,
    name: '달빛베이커리',
    districtId: 'haeundae',
    address: '부산 해운대구 달맞이길 45',
    signatureMenu: '크림치즈 바게트',
    rating: 4.2,
    heartCount: 98,
    tags: ['바게트', '뷰맛집'],
    emoji: '🥖',
    description: '바다뷰와 함께 즐기는 바게트 샌드위치.',
  },
  {
    id: 3,
    name: '모래사장 크로플',
    districtId: 'haeundae',
    address: '부산 해운대구 우동 87',
    signatureMenu: '시그니처 크로플',
    rating: 4.0,
    heartCount: 76,
    tags: ['크로플', '디저트'],
    emoji: '🧇',
    description: '바삭한 크로플에 젤라또를 얹은 인기 디저트.',
  },
  {
    id: 4,
    name: '서면 크루아상연구소',
    districtId: 'seomyeon',
    address: '부산 부산진구 서면로 22',
    signatureMenu: '버터 크루아상',
    rating: 4.7,
    heartCount: 305,
    tags: ['크루아상', '오픈런'],
    emoji: '🥐',
    description: '겹겹이 살아있는 크루아상 장인의 가게.',
  },
  {
    id: 5,
    name: '골목빵집 서면점',
    districtId: 'seomyeon',
    address: '부산 부산진구 전포대로 5',
    signatureMenu: '단팥크림빵',
    rating: 4.1,
    heartCount: 64,
    tags: ['단팥빵', '옛날빵'],
    emoji: '🍞',
    description: '옛날 감성 그대로의 단팥크림빵.',
  },
  {
    id: 6,
    name: '전포 소금빵하우스',
    districtId: 'seomyeon',
    address: '부산 부산진구 전포동 158',
    signatureMenu: '통모짜 소금빵',
    rating: 4.4,
    heartCount: 140,
    tags: ['소금빵', '치즈'],
    emoji: '🧂',
    description: '치즈를 듬뿍 넣은 통모짜 소금빵이 인기.',
  },
  {
    id: 7,
    name: '남포동 옛날식빵',
    districtId: 'nampodong',
    address: '부산 중구 남포동 33',
    signatureMenu: '우유식빵',
    rating: 4.3,
    heartCount: 121,
    tags: ['식빵', '옛날빵'],
    emoji: '🍞',
    description: '50년 전통 그대로의 폭신한 우유식빵.',
  },
  {
    id: 8,
    name: '자갈치 도넛공작소',
    districtId: 'nampodong',
    address: '부산 중구 자갈치로 8',
    signatureMenu: '수제 찹쌀도넛',
    rating: 4.0,
    heartCount: 58,
    tags: ['도넛', '길거리간식'],
    emoji: '🍩',
    description: '쫀득한 찹쌀도넛을 즉석에서 튀겨준다.',
  },
  {
    id: 9,
    name: '깡통시장 딸기케이크',
    districtId: 'nampodong',
    address: '부산 중구 깡통시장길 19',
    signatureMenu: '딸기생크림케이크',
    rating: 4.6,
    heartCount: 189,
    tags: ['딸기', '시즌한정'],
    emoji: '🍓',
    description: '딸기 시즌에만 만나볼 수 있는 인기 케이크.',
  },
  {
    id: 10,
    name: '광안리 파도베이커리',
    districtId: 'gwangalli',
    address: '부산 수영구 광안해변로 210',
    signatureMenu: '피낭시에 세트',
    rating: 4.2,
    heartCount: 87,
    tags: ['피낭시에', '뷰맛집'],
    emoji: '🌊',
    description: '광안대교 뷰가 예술인 피낭시에 맛집.',
  },
  {
    id: 11,
    name: '민락동 새벽빵집',
    districtId: 'gwangalli',
    address: '부산 수영구 민락동 44',
    signatureMenu: '모닝빵 세트',
    rating: 4.3,
    heartCount: 102,
    tags: ['오픈런', '새벽빵'],
    emoji: '🌅',
    description: '새벽 6시부터 갓 구운 빵이 쏟아지는 곳.',
  },
  {
    id: 12,
    name: '동래 한옥빵집',
    districtId: 'dongnae',
    address: '부산 동래구 동래로 77',
    signatureMenu: '흑임자 앙버터',
    rating: 4.5,
    heartCount: 156,
    tags: ['앙버터', '전통'],
    emoji: '⛩️',
    description: '한옥 카페에서 즐기는 흑임자 앙버터빵.',
  },
  {
    id: 13,
    name: '온천장 크림빵',
    districtId: 'dongnae',
    address: '부산 동래구 온천장로 3',
    signatureMenu: '온천 크림빵',
    rating: 4.0,
    heartCount: 49,
    tags: ['크림빵', '로컬맛집'],
    emoji: '🍞',
    description: '동래온천 나들이 후 들르기 좋은 크림빵집.',
  },
]
