export const COMMUNITY_POSTS = [
  {
    id: 1,
    categoryId: 'today-visit',
    title: '오늘 서면 크루아상연구소 다녀왔어요',
    author: '단팥소보로',
    content: '오픈 30분 만에 크루아상 다 팔릴 뻔... 겨우 득템했습니다. 겹겹이 살아있고 버터향이 진해요.',
    heartCount: 34,
    commentCount: 8,
    createdAt: '2026-07-14',
    emoji: '🥐',
  },
  {
    id: 2,
    categoryId: 'today-visit',
    title: '남포동 옛날식빵 방금 사왔어요',
    author: '식빵요정',
    content: '줄 서서 산 우유식빵, 집 가는 길에 다 먹을 뻔했어요. 완전 폭신폭신.',
    heartCount: 21,
    commentCount: 4,
    createdAt: '2026-07-14',
    emoji: '🍞',
  },
  {
    id: 3,
    categoryId: 'new-menu',
    title: '전포 소금빵하우스 통모짜 신메뉴 후기',
    author: '치즈러버',
    content: '치즈가 실처럼 늘어나요. 소금빵 위에 치즈 토핑 신메뉴 강추합니다.',
    heartCount: 45,
    commentCount: 12,
    createdAt: '2026-07-13',
    emoji: '🧂',
  },
  {
    id: 4,
    categoryId: 'new-menu',
    title: '깡통시장 딸기케이크 시즌 신메뉴 나왔어요',
    author: '딸기덕후',
    content: '이번엔 딸기라떼 크림까지 추가됐다는 소식! 당장 달려갑니다.',
    heartCount: 58,
    commentCount: 15,
    createdAt: '2026-07-12',
    emoji: '🍓',
  },
  {
    id: 5,
    categoryId: 'open-run',
    title: '민락동 새벽빵집 오픈런 성공!',
    author: '새벽러너',
    content: '새벽 5시 50분에 도착해서 1등으로 모닝빵 세트 득템했습니다 ㅎㅎ',
    heartCount: 67,
    commentCount: 20,
    createdAt: '2026-07-11',
    emoji: '🌅',
  },
  {
    id: 6,
    categoryId: 'open-run',
    title: '해운대 소금빵공방 오픈런 팁 공유',
    author: '소금빵마스터',
    content: '평일 오전 8시 전에 가면 웨이팅 없이 살 수 있어요. 주말은 필수 오픈런!',
    heartCount: 52,
    commentCount: 9,
    createdAt: '2026-07-10',
    emoji: '🥐',
  },
  {
    id: 7,
    categoryId: 'recommend',
    title: '부산 여행 온다면 이 빵집들 꼭 가세요',
    author: '빵지순례자',
    content: '해운대, 남포동, 서면 빵집 코스 추천 정리했어요. 하루 코스로 딱 좋습니다.',
    heartCount: 89,
    commentCount: 25,
    createdAt: '2026-07-09',
    emoji: '🙌',
  },
  {
    id: 8,
    categoryId: 'photo',
    title: '광안리 파도베이커리 뷰 미쳤어요 📸',
    author: '뷰맛집헌터',
    content: '광안대교 배경으로 피낭시에 찍으니 인생샷 나왔습니다.',
    heartCount: 73,
    commentCount: 11,
    createdAt: '2026-07-08',
    emoji: '🌊',
  },
  {
    id: 9,
    categoryId: 'photo',
    title: '동래 한옥빵집 감성샷 모음',
    author: '한옥러버',
    content: '한옥 마당에서 흑임자 앙버터빵과 함께 찍은 사진 공유해요.',
    heartCount: 41,
    commentCount: 6,
    createdAt: '2026-07-07',
    emoji: '⛩️',
  },
]
